<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260211123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Allow filtering smartsheet duration pivot columns.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP PROCEDURE IF EXISTS repweb.sp_smartsheet_site_task_duration_pivot');
        $this->addSql('DROP PROCEDURE IF EXISTS nifi.sp_smartsheet_site_task_duration_pivot');
        $this->addSql(
            "CREATE DEFINER=`webuser`@`%` PROCEDURE `nifi`.`sp_smartsheet_site_task_duration_pivot`(IN p_columns TEXT)\n"
            . "BEGIN\n"
            . "  DECLARE cols TEXT;\n"
            . "  DECLARE cols_normalized TEXT;\n"
            . "  DECLARE show_duration TINYINT(1);\n"
            . "  DECLARE show_start_date TINYINT(1);\n"
            . "  DECLARE show_end_date TINYINT(1);\n"
            . "  DECLARE show_pct_complete TINYINT(1);\n\n"
            . "  SET cols_normalized = LOWER(REPLACE(IFNULL(p_columns, ''), ' ', ''));\n"
            . "  SET show_duration = FIND_IN_SET('duration', cols_normalized) > 0;\n"
            . "  SET show_start_date = FIND_IN_SET('start_date', cols_normalized) > 0;\n"
            . "  SET show_end_date = FIND_IN_SET('end_date', cols_normalized) > 0;\n"
            . "  SET show_pct_complete = FIND_IN_SET('pct_complete', cols_normalized) > 0;\n\n"
            . "  IF show_duration = 0 AND show_start_date = 0 AND show_end_date = 0 AND show_pct_complete = 0 THEN\n"
            . "    SET show_duration = 1;\n"
            . "    SET show_start_date = 1;\n"
            . "    SET show_end_date = 1;\n"
            . "    SET show_pct_complete = 1;\n"
            . "  END IF;\n\n"
            . "  SELECT GROUP_CONCAT(\n"
            . "           CONCAT(\n"
            . "             IF(show_duration,\n"
            . "               CONCAT(\n"
            . "                 'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "                 ' THEN DATEDIFF(end_date, start_date) END) AS `',\n"
            . "                 REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "                 '_duration`'\n"
            . "               ),\n"
            . "               ''\n"
            . "             ),\n"
            . "             IF(show_start_date,\n"
            . "               CONCAT(\n"
            . "                 IF(show_duration, ', ', ''),\n"
            . "                 'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "                 ' THEN DATE_FORMAT(start_date, ''%Y-%m-%d'') END) AS `',\n"
            . "                 REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "                 '_start_date`'\n"
            . "               ),\n"
            . "               ''\n"
            . "             ),\n"
            . "             IF(show_end_date,\n"
            . "               CONCAT(\n"
            . "                 IF(show_duration OR show_start_date, ', ', ''),\n"
            . "                 'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "                 ' THEN DATE_FORMAT(end_date, ''%Y-%m-%d'') END) AS `',\n"
            . "                 REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "                 '_end_date`'\n"
            . "               ),\n"
            . "               ''\n"
            . "             ),\n"
            . "             IF(show_pct_complete,\n"
            . "               CONCAT(\n"
            . "                 IF(show_duration OR show_start_date OR show_end_date, ', ', ''),\n"
            . "                 'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "                 ' THEN `%_complete` END) AS `',\n"
            . "                 REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "                 '_pct_complete`'\n"
            . "               ),\n"
            . "               ''\n"
            . "             )\n"
            . "           )\n"
            . "           ORDER BY min_row_num\n"
            . "           SEPARATOR ', '\n"
            . "         )\n"
            . "    INTO cols\n"
            . "  FROM (\n"
            . "    SELECT task_name, MIN(row_num) AS min_row_num\n"
            . "    FROM nifi.smartsheet_master_data\n"
            . "    WHERE IFNULL(phase, '') NOT IN ('Store','Country')\n"
            . "      AND task_name IS NOT NULL\n"
            . "      AND task_name <> ''\n"
            . "    GROUP BY task_name\n"
            . "  ) t;\n\n"
            . "  SET @sql = CONCAT(\n"
            . "    'SELECT ',\n"
            . "      'COALESCE(NULLIF(TRIM(country), ''''), '''') AS country_abbr, ',\n"
            . "      'TRIM(REPLACE(REPLACE(REPLACE(site_name, ''IKEAStore - '', ''''), ''IKEA - '', ''''), ''Store - '', '''')) AS site_name_clean, ',\n"
            . "      'CONCAT(COALESCE(NULLIF(TRIM(country), ''''), ''''), '' '', ',\n"
            . "        'TRIM(REPLACE(REPLACE(REPLACE(site_name, ''IKEAStore - '', ''''), ''IKEA - '', ''''), ''Store - '', ''''))',\n"
            . "      ') AS site_label, ',\n"
            . "      cols, ' ',\n"
            . "    'FROM nifi.smartsheet_master_data ',\n"
            . "    'WHERE IFNULL(phase, '''') NOT IN (''Store'',''Country'') ',\n"
            . "    'GROUP BY country_abbr, site_name_clean, site_label ',\n"
            . "    'ORDER BY country_abbr, site_name_clean'\n"
            . "  );\n\n"
            . "  PREPARE stmt FROM @sql;\n"
            . "  EXECUTE stmt;\n"
            . "  DEALLOCATE PREPARE stmt;\n"
            . "END"
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP PROCEDURE IF EXISTS repweb.sp_smartsheet_site_task_duration_pivot');
        $this->addSql('DROP PROCEDURE IF EXISTS nifi.sp_smartsheet_site_task_duration_pivot');
        $this->addSql(
            "CREATE DEFINER=`webuser`@`%` PROCEDURE `nifi`.`sp_smartsheet_site_task_duration_pivot`()\n"
            . "BEGIN\n"
            . "  DECLARE cols TEXT;\n\n"
            . "  SELECT GROUP_CONCAT(\n"
            . "           CONCAT(\n"
            . "             'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "             ' THEN DATEDIFF(end_date, start_date) END) AS `',\n"
            . "             REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "             '_duration`',\n"
            . "             ', ',\n"
            . "             'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "             ' THEN DATE_FORMAT(start_date, ''%Y-%m-%d'') END) AS `',\n"
            . "             REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "             '_start_date`',\n"
            . "             ', ',\n"
            . "             'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "             ' THEN DATE_FORMAT(end_date, ''%Y-%m-%d'') END) AS `',\n"
            . "             REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "             '_end_date`',\n"
            . "             ', ',\n"
            . "             'MAX(CASE WHEN task_name = ', QUOTE(task_name),\n"
            . "             ' THEN `%_complete` END) AS `',\n"
            . "             REPLACE(REPLACE(REPLACE(REPLACE(task_name,'`',''),'/', '_'),' ', '_'), '-', '_'),\n"
            . "             '_pct_complete`'\n"
            . "           )\n"
            . "           ORDER BY min_row_num\n"
            . "           SEPARATOR ', '\n"
            . "         )\n"
            . "    INTO cols\n"
            . "  FROM (\n"
            . "    SELECT task_name, MIN(row_num) AS min_row_num\n"
            . "    FROM nifi.smartsheet_master_data\n"
            . "    WHERE IFNULL(phase, '') NOT IN ('Store','Country')\n"
            . "      AND task_name IS NOT NULL\n"
            . "      AND task_name <> ''\n"
            . "    GROUP BY task_name\n"
            . "  ) t;\n\n"
            . "  SET @sql = CONCAT(\n"
            . "    'SELECT ',\n"
            . "      'COALESCE(NULLIF(TRIM(country), ''''), '''') AS country_abbr, ',\n"
            . "      'TRIM(REPLACE(REPLACE(REPLACE(site_name, ''IKEAStore - '', ''''), ''IKEA - '', ''''), ''Store - '', '''')) AS site_name_clean, ',\n"
            . "      'CONCAT(COALESCE(NULLIF(TRIM(country), ''''), ''''), '' '', ',\n"
            . "        'TRIM(REPLACE(REPLACE(REPLACE(site_name, ''IKEAStore - '', ''''), ''IKEA - '', ''''), ''Store - '', ''''))',\n"
            . "      ') AS site_label, ',\n"
            . "      cols, ' ',\n"
            . "    'FROM nifi.smartsheet_master_data ',\n"
            . "    'WHERE IFNULL(phase, '''') NOT IN (''Store'',''Country'') ',\n"
            . "    'GROUP BY country_abbr, site_name_clean, site_label ',\n"
            . "    'ORDER BY country_abbr, site_name_clean'\n"
            . "  );\n\n"
            . "  PREPARE stmt FROM @sql;\n"
            . "  EXECUTE stmt;\n"
            . "  DEALLOCATE PREPARE stmt;\n"
            . "END"
        );
    }
}
