controllers:
  resource: ../src/Controller/
  type: attribute
# config/routes.yaml
dt_export:
  path: /api/dt/{reportId}/export.{format}
  controller: App\Controller\ExportController::export
  methods: [POST]
  requirements:
    format: xlsx|csv
# config/routes.yaml
report_api:
  path: /api/report/{reportId}.{format}
  controller: App\Controller\ReportApiController::fetch
  requirements: { format: json|csv }
  methods: [GET]
