parameters: { }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Load everything in src/ (relative to config/services.yaml)
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # Controllers must be public & tagged so they’re callable
  App\Controller\:
    resource: '../src/Controller/'
    public: true
    tags: ['controller.service_arguments']
